/**
 * Single source of truth for app destinations — the home quick-actions
 * grid and the side drawer used to maintain two separate, drifting lists
 * of the same routes.
 */

export const NAV_ITEMS = [
  {
    key: 'timetable',
    label: 'Timetable',
    icon: 'time-outline',
    colorKey: 'primary',
    route: '/timetable',
    showInDrawer: true,
    showInQuickActions: true,
  },
  {
    key: 'exams',
    label: 'Exams',
    icon: 'document-text-outline',
    colorKey: 'red',
    route: '/exams',
    showInDrawer: false,
    showInQuickActions: true,
  },
  {
    key: 'notices',
    label: 'Notices',
    icon: 'notifications-outline',
    colorKey: 'yellow',
    route: '/notices',
    badge: true,
    showInDrawer: false,
    showInQuickActions: true,
  },
  {
    key: 'activity',
    label: 'Activity',
    icon: 'heart-outline',
    colorKey: 'red',
    route: '/notifications',
    badge: true,
    showInDrawer: true,
    showInQuickActions: true,
  },
  {
    key: 'documents',
    label: 'My Documents',
    drawerLabel: 'iVault',
    icon: 'folder-outline',
    colorKey: 'green',
    route: '/documents',
    showInDrawer: true,
    showInQuickActions: true,
  },
  {
    key: 'forums',
    label: 'Forums',
    drawerLabel: 'Community',
    icon: 'chatbubbles-outline',
    colorKey: 'primary',
    route: '/community',
    showInDrawer: false,
    showInQuickActions: true,
  },
  {
    key: 'chambers',
    label: 'Chambers',
    icon: 'people-outline',
    colorKey: 'green',
    route: '/community',
    showInDrawer: false,
    showInQuickActions: true,
  },
  {
    key: 'reels',
    label: 'Reels',
    icon: 'play-circle-outline',
    colorKey: 'red',
    route: '/reels',
    showInDrawer: false,
    showInQuickActions: true,
  },
  {
    key: 'events',
    label: 'Events',
    drawerLabel: 'Clubs & Events',
    icon: 'calendar-outline',
    colorKey: 'blue',
    route: '/clubs',
    showInDrawer: true,
    showInQuickActions: true,
  },
  {
    key: 'ai',
    label: 'iAI',
    drawerLabel: 'iAI Assistant',
    icon: 'sparkles-outline',
    colorKey: 'primary',
    route: '/ai',
    showInDrawer: true,
    showInQuickActions: true,
  },
  {
    key: 'career',
    label: 'iCareer',
    icon: 'briefcase-outline',
    colorKey: 'green',
    route: '/career',
    showInDrawer: true,
    showInQuickActions: false,
  },
  {
    key: 'portfolio',
    label: 'My Portfolio',
    icon: 'person-circle-outline',
    colorKey: 'blue',
    route: '/portfolio',
    showInDrawer: true,
    showInQuickActions: false,
  },
  {
    key: 'library',
    label: 'Library',
    icon: 'book-outline',
    colorKey: 'blue',
    showInDrawer: true,
    showInQuickActions: true,
    soon: true,
  },
  {
    key: 'settings',
    label: 'Settings',
    icon: 'settings-outline',
    colorKey: 'textSecondary',
    showInDrawer: true,
    showInQuickActions: false,
    soon: true,
  },
  {
    key: 'adminConsole',
    label: 'Admin Console',
    icon: 'shield-checkmark-outline',
    colorKey: 'primary',
    route: '/admin',
    roles: ['university_admin', 'platform_admin'],
    showInDrawer: true,
    showInQuickActions: false,
  },
  {
    key: 'lecturerConsole',
    label: 'Lecturer Console',
    icon: 'easel-outline',
    colorKey: 'blue',
    route: '/lecturer',
    roles: ['lecturer'],
    showInDrawer: true,
    showInQuickActions: false,
  },
  {
    key: 'clubAdminConsole',
    label: 'Club Console',
    icon: 'people-circle-outline',
    colorKey: 'green',
    route: '/club-admin',
    roles: ['club_admin'],
    showInDrawer: true,
    showInQuickActions: false,
  },
  {
    key: 'employerConsole',
    label: 'Employer Console',
    icon: 'briefcase-outline',
    colorKey: 'orange',
    route: '/employer',
    roles: ['employer'],
    showInDrawer: true,
    showInQuickActions: false,
  },
];
